# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-16.04

steps:
- script: mkdir ~/testing7890
  displayName: 'Run a one-line script'

- script: |
    echo mkdir ~/testing7890
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
